### ISSUE TITLE
Clan member list sorting broken

### ISSUE THREAD

**Issue by YvesW** [jodelahithit/runelite-plugins#13]
Since today, clan member list sorting seems to be broken for me. It either hides or infinitely refreshes the clan list.
I feel like there's been an update to the API that might cause it, but I can't find the RL commit. Also don't know if changing the panel due to the PvP arena grouping option changed anything.

Issue in action:
https://gfycat.com/AdoredPeriodicHen

![afbeelding](https://user-images.githubusercontent.com/7929021/177821301-cf327a09-115f-4cc4-bb27-519a2c71b8f3.png)

Remained after client restart. Only way to fix it is to disable the plugin, then refresh the CC list.

This is the only thing that shows up in my client.log (I ctrl+f'd for clanmemberlistsort)
`2022-07-07 17:42:25 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at eu.jodelahithit.clanmemberlistsort.ClanMemberListSortPlugin.onScriptPostFired(ClanMemberListSortPlugin.java:82)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:179)
	at client.lj(client.java:52095)
	at ea.v(ea.java:49082)
	at hi.c(hi.java:116)
	at client.wf(client.java:3321)
	at client.ab(client.java:1127)
	at ap.m(ap.java:338)
	at ap.run(ap.java:317)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-07-07 17:42:26 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: null`

**Comment by jodelahithit** [comment]
Thank you so much for the report. I've had multiple reports today but unfortunately the issue is very difficult to debug because of the 'hacky' nature of the plugin. I've opened a pull request with some additional checks so I can hopefully properly debug the issue. Feel free to send me your log in a few days if the issue is still occurring. It might be very valuable!

**Comment by YvesW** [comment]
@jodelahithit I noticed that NFC merged the PR yesterday. Works great again; thank you very much for fixing it!

**Comment by erwinvc** [comment]
Glad to hear that fixed the issue! Thanks again for bringing it to my attention.
